"""track clicks

Revision ID: 008bacbec985
Revises: 65d10f523ee5
Create Date: 2026-01-29 23:21:39.566466

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "008bacbec985"
down_revision = "65d10f523ee5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "click",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tracking_id", sa.String(length=128), nullable=False),
        sa.Column("click_count", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("provider_supabase_id", sa.String(length=64), nullable=True),
        sa.Column("family_supabase_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "provider_supabase_id IS NOT NULL OR family_supabase_id IS NOT NULL", name="click_requires_user_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_supabase_id", "tracking_id", name="tracking_id_family"),
        sa.UniqueConstraint("provider_supabase_id", "tracking_id", name="tracking_id_provider"),
    )
    with op.batch_alter_table("click", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_click_family_supabase_id"), ["family_supabase_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_click_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_click_provider_supabase_id"), ["provider_supabase_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_click_tracking_id"), ["tracking_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("click", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_click_tracking_id"))
        batch_op.drop_index(batch_op.f("ix_click_provider_supabase_id"))
        batch_op.drop_index(batch_op.f("ix_click_id"))
        batch_op.drop_index(batch_op.f("ix_click_family_supabase_id"))

    op.drop_table("click")
    # ### end Alembic commands ###
