"""Add hours to lump sum

Revision ID: 031eaafe7671
Revises: bbae7ef6a804
Create Date: 2025-08-22 10:06:31.554760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031eaafe7671'
down_revision = 'bbae7ef6a804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocated_lump_sum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocated_lump_sum', schema=None) as batch_op:
        batch_op.drop_column('hours')

    # ### end Alembic commands ###
