"""track link clicks

Revision ID: 0bc1185673cf
Revises: 65d10f523ee5
Create Date: 2026-01-28 23:28:46.177426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc1185673cf'
down_revision = '65d10f523ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_click_track',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=False),
    sa.Column('provider_supabase_id', sa.String(length=64), nullable=True),
    sa.Column('family_supabase_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_supabase_id', 'link', name='link_family'),
    sa.UniqueConstraint('provider_supabase_id', 'link', name='link_provider')
    )
    with op.batch_alter_table('link_click_track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_click_track_family_supabase_id'), ['family_supabase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_link_click_track_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_link_click_track_provider_supabase_id'), ['provider_supabase_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_click_track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_click_track_provider_supabase_id'))
        batch_op.drop_index(batch_op.f('ix_link_click_track_id'))
        batch_op.drop_index(batch_op.f('ix_link_click_track_family_supabase_id'))

    op.drop_table('link_click_track')
    # ### end Alembic commands ###
