"""Add AllocatedLumpSum

Revision ID: 181a220fb42b
Revises: f809a5b2bc15
Create Date: 2025-08-15 14:19:31.231640

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "181a220fb42b"
down_revision = "f809a5b2bc15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocated_lump_sum",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("care_month_allocation_id", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("provider_google_sheets_id", sa.String(length=64), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["care_month_allocation_id"],
            ["month_allocation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("allocated_lump_sum", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_allocated_lump_sum_provider_google_sheets_id"), ["provider_google_sheets_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocated_lump_sum", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_allocated_lump_sum_provider_google_sheets_id"))

    op.drop_table("allocated_lump_sum")
    # ### end Alembic commands ###
