"""provider invitation

Revision ID: 1b40b8ada6d4
Revises: fdad39e7d357
Create Date: 2025-08-01 22:36:12.069577

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1b40b8ada6d4"
down_revision = "fdad39e7d357"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_invitation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=True),
        sa.Column("child_google_sheet_id", sa.String(length=64), nullable=True),
        sa.Column("invite_email", sa.String(length=254), nullable=False),
        sa.Column("email_sent", sa.Boolean(), nullable=False),
        sa.Column("sms_sent", sa.Boolean(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("provider_invitation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_provider_invitation_child_google_sheet_id"), ["child_google_sheet_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_provider_invitation_public_id"), ["public_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider_invitation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_invitation_public_id"))
        batch_op.drop_index(batch_op.f("ix_provider_invitation_child_google_sheet_id"))

    op.drop_table("provider_invitation")
    # ### end Alembic commands ###
