"""Add UserActivity model

Revision ID: 1d5324678518
Revises: 74e5649e1daf
Create Date: 2025-10-08 18:34:32.671033

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1d5324678518"
down_revision = "74e5649e1daf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_activity",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hour", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_supabase_id", sa.String(length=64), nullable=True),
        sa.Column("family_supabase_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_supabase_id", "hour", name="unique_family_hour"),
        sa.UniqueConstraint("provider_supabase_id", "hour", name="unique_provider_hour"),
    )
    with op.batch_alter_table("user_activity", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_activity_family_supabase_id"), ["family_supabase_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_activity_hour"), ["hour"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_activity_provider_supabase_id"), ["provider_supabase_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_activity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_activity_provider_supabase_id"))
        batch_op.drop_index(batch_op.f("ix_user_activity_hour"))
        batch_op.drop_index(batch_op.f("ix_user_activity_family_supabase_id"))

    op.drop_table("user_activity")
    # ### end Alembic commands ###
