"""Add unique constraint to AllocatedCareDay

Revision ID: 2db51e2690c4
Revises: a4197b58cd55
Create Date: 2025-08-05 11:55:11.479312

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2db51e2690c4"
down_revision = "a4197b58cd55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocated_care_day", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("unique_allocation_date"), type_="unique")
        batch_op.create_unique_constraint(
            "unique_allocation_provider_date", ["care_month_allocation_id", "provider_google_sheets_id", "date"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocated_care_day", schema=None) as batch_op:
        batch_op.drop_constraint("unique_allocation_provider_date", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("unique_allocation_date"),
            ["care_month_allocation_id", "date"],
            postgresql_nulls_not_distinct=False,
        )

    # ### end Alembic commands ###
