"""timestamp when initialization happened

Revision ID: 35e5058b5596
Revises: 88278629a5bc
Create Date: 2025-09-02 20:16:29.538201

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "35e5058b5596"
down_revision = "88278629a5bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider_payment_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("card_initialization_attempted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("ach_initialization_attempted_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider_payment_settings", schema=None) as batch_op:
        batch_op.drop_column("ach_initialization_attempted_at")
        batch_op.drop_column("card_initialization_attempted_at")

    # ### end Alembic commands ###
