"""internal

Revision ID: 4b42dbdfc60a
Revises: 4d8a552d6805
Create Date: 2025-09-19 21:01:19.087695

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b42dbdfc60a"
down_revision = "4d8a552d6805"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_internal", sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f("ix_email_log_is_internal"), ["is_internal"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_log_is_internal"))
        batch_op.drop_column("is_internal")

    # ### end Alembic commands ###
