"""attendance

Revision ID: 4bc01c5a2653
Revises: f809a5b2bc15
Create Date: 2025-08-14 14:45:52.252555

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4bc01c5a2653"
down_revision = "f809a5b2bc15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("week", sa.Date(), nullable=False),
        sa.Column("child_google_sheet_id", sa.String(length=64), nullable=True),
        sa.Column("provider_google_sheet_id", sa.String(length=64), nullable=True),
        sa.Column("family_entered_hours", sa.Integer(), nullable=True),
        sa.Column("family_entered_at", sa.DateTime(), nullable=True),
        sa.Column("provider_entered_hours", sa.Integer(), nullable=True),
        sa.Column("provider_entered_at", sa.DateTime(), nullable=True),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendance_child_google_sheet_id"), ["child_google_sheet_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_provider_google_sheet_id"), ["provider_google_sheet_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_attendance_week"), ["week"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_week"))
        batch_op.drop_index(batch_op.f("ix_attendance_provider_google_sheet_id"))
        batch_op.drop_index(batch_op.f("ix_attendance_child_google_sheet_id"))

    op.drop_table("attendance")
    # ### end Alembic commands ###
