"""email log model

Revision ID: 4d8a552d6805
Revises: e8385996b8f1
Create Date: 2025-09-19 20:34:10.963314

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d8a552d6805"
down_revision = "e8385996b8f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("from_email", sa.String(length=255), nullable=False),
        sa.Column("to_emails", sa.JSON(), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("html_content", sa.Text(), nullable=False),
        sa.Column("from_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("sendgrid_message_id", sa.String(length=100), nullable=True),
        sa.Column("sendgrid_status_code", sa.Integer(), nullable=True),
        sa.Column("email_type", sa.String(length=50), nullable=True),
        sa.Column("context_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_email_log_email_type"), ["email_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_log_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_log_status"), ["status"], unique=False)

    with op.batch_alter_table("payment_rate", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("unique_provider_child_rate"), type_="unique")
        batch_op.create_unique_constraint("unique_provider_child_rate", ["provider_supabase_id", "child_supabase_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_rate", schema=None) as batch_op:
        batch_op.drop_constraint("unique_provider_child_rate", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("unique_provider_child_rate"),
            ["google_sheets_provider_id", "google_sheets_child_id"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("email_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_log_status"))
        batch_op.drop_index(batch_op.f("ix_email_log_id"))
        batch_op.drop_index(batch_op.f("ix_email_log_email_type"))

    op.drop_table("email_log")
    # ### end Alembic commands ###
