"""track reclaimed funds

Revision ID: 65d10f523ee5
Revises: d6434d09ed2f
Create Date: 2025-12-04 22:45:42.497542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d10f523ee5'
down_revision = 'd6434d09ed2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_reclamation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('chek_transfer_id', sa.String(length=64), nullable=True),
    sa.Column('chek_user_id', sa.String(length=64), nullable=True),
    sa.Column('month_allocation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['month_allocation_id'], ['month_allocation.id'], name='fk_payment_month_allocation_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_reclamation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fund_reclamation_chek_transfer_id'), ['chek_transfer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_reclamation_chek_user_id'), ['chek_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_reclamation_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_reclamation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_reclamation_id'))
        batch_op.drop_index(batch_op.f('ix_fund_reclamation_chek_user_id'))
        batch_op.drop_index(batch_op.f('ix_fund_reclamation_chek_transfer_id'))

    op.drop_table('fund_reclamation')
    # ### end Alembic commands ###
