"""Make care_days_count on PaymentRequest nullable=False

Revision ID: 6d78d0d0cf80
Revises: a4197b58cd55
Create Date: 2025-08-04 18:29:23.296088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d78d0d0cf80'
down_revision = 'a4197b58cd55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.alter_column('care_days_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.alter_column('care_days_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
