"""attendancedays

Revision ID: 74e5649e1daf
Revises: af5c75ad4789
Create Date: 2025-10-02 20:33:12.377669

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "74e5649e1daf"
down_revision = "af5c75ad4789"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("family_entered_full_days", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("family_entered_half_days", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("provider_entered_full_days", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("provider_entered_half_days", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.drop_column("provider_entered_half_days")
        batch_op.drop_column("provider_entered_full_days")
        batch_op.drop_column("family_entered_half_days")
        batch_op.drop_column("family_entered_full_days")

    # ### end Alembic commands ###
