"""payment models

Revision ID: 74fb34cdd755
Revises: 9ee0cfc6b76f
Create Date: 2025-08-29 18:57:36.584719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74fb34cdd755'
down_revision = '9ee0cfc6b76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_payment_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_external_id', sa.String(length=64), nullable=True),
    sa.Column('chek_user_id', sa.String(length=64), nullable=True),
    sa.Column('chek_wallet_balance', sa.Integer(), nullable=True),
    sa.Column('last_chek_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_payment_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_payment_settings_chek_user_id'), ['chek_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_payment_settings_family_external_id'), ['family_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_payment_settings_id'), ['id'], unique=False)

    op.create_table('provider_payment_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_external_id', sa.String(length=64), nullable=True),
    sa.Column('chek_user_id', sa.String(length=64), nullable=True),
    sa.Column('chek_direct_pay_id', sa.String(length=64), nullable=True),
    sa.Column('chek_direct_pay_status', sa.String(length=32), nullable=True),
    sa.Column('chek_card_id', sa.String(length=64), nullable=True),
    sa.Column('chek_card_status', sa.String(length=32), nullable=True),
    sa.Column('chek_wallet_balance', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('CARD', 'ACH', name='paymentmethod'), nullable=True),
    sa.Column('payment_method_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_chek_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_payment_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_payment_settings_chek_card_id'), ['chek_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_payment_settings_chek_direct_pay_id'), ['chek_direct_pay_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_payment_settings_chek_user_id'), ['chek_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_payment_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_payment_settings_provider_external_id'), ['provider_external_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_provider_id', sa.String(length=64), nullable=False),
    sa.Column('external_child_id', sa.String(length=64), nullable=True),
    sa.Column('provider_payment_settings_id', sa.UUID(), nullable=False),
    sa.Column('family_payment_settings_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'ACH', name='paymentmethod'), nullable=False),
    sa.Column('month_allocation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_payment_settings_id'], ['family_payment_settings.id'], name='fk_payment_family_settings_id'),
    sa.ForeignKeyConstraint(['month_allocation_id'], ['month_allocation.id'], name='fk_payment_month_allocation_id'),
    sa.ForeignKeyConstraint(['provider_payment_settings_id'], ['provider_payment_settings.id'], name='fk_payment_provider_settings_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_external_child_id'), ['external_child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_external_provider_id'), ['external_provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_id'), ['id'], unique=False)

    op.create_table('payment_intent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_external_id', sa.String(length=64), nullable=False),
    sa.Column('child_external_id', sa.String(length=64), nullable=True),
    sa.Column('month_allocation_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('care_day_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('lump_sum_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_payment_settings_id', sa.UUID(), nullable=False),
    sa.Column('family_payment_settings_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_payment_settings_id'], ['family_payment_settings.id'], name='fk_payment_intent_family_settings_id'),
    sa.ForeignKeyConstraint(['month_allocation_id'], ['month_allocation.id'], name='fk_payment_intent_month_allocation_id'),
    sa.ForeignKeyConstraint(['provider_payment_settings_id'], ['provider_payment_settings.id'], name='fk_payment_intent_provider_settings_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_intent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_intent_child_external_id'), ['child_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_intent_provider_external_id'), ['provider_external_id'], unique=False)

    op.create_table('payment_attempt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'ACH', name='paymentmethod'), nullable=False),
    sa.Column('family_chek_user_id', sa.String(length=64), nullable=True),
    sa.Column('provider_chek_user_id', sa.String(length=64), nullable=True),
    sa.Column('provider_chek_card_id', sa.String(length=64), nullable=True),
    sa.Column('provider_chek_direct_pay_id', sa.String(length=64), nullable=True),
    sa.Column('wallet_transfer_id', sa.String(length=64), nullable=True),
    sa.Column('wallet_transfer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ach_payment_id', sa.String(length=64), nullable=True),
    sa.Column('ach_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_transfer_id', sa.String(length=64), nullable=True),
    sa.Column('card_transfer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name='fk_payment_attempt_payment_id'),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intent.id'], name='fk_payment_attempt_intent_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_attempt_ach_payment_id'), ['ach_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_attempt_card_transfer_id'), ['card_transfer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_attempt_family_chek_user_id'), ['family_chek_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_attempt_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_attempt_provider_chek_card_id'), ['provider_chek_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_attempt_provider_chek_direct_pay_id'), ['provider_chek_direct_pay_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_attempt_provider_chek_user_id'), ['provider_chek_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_attempt_wallet_transfer_id'), ['wallet_transfer_id'], unique=False)

    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_allocated_care_day_payment_id', 'payment', ['payment_id'], ['id'])

    with op.batch_alter_table('allocated_lump_sum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_allocated_lump_sum_payment_id', 'payment', ['payment_id'], ['id'])

    with op.batch_alter_table('month_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chek_transfer_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('chek_transfer_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_month_allocation_chek_transfer_id'), ['chek_transfer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('month_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_month_allocation_chek_transfer_id'))
        batch_op.drop_column('chek_transfer_date')
        batch_op.drop_column('chek_transfer_id')

    with op.batch_alter_table('allocated_lump_sum', schema=None) as batch_op:
        batch_op.drop_constraint('fk_allocated_lump_sum_payment_id', type_='foreignkey')
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.drop_constraint('fk_allocated_care_day_payment_id', type_='foreignkey')
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('payment_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_attempt_wallet_transfer_id'))
        batch_op.drop_index(batch_op.f('ix_payment_attempt_provider_chek_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_attempt_provider_chek_direct_pay_id'))
        batch_op.drop_index(batch_op.f('ix_payment_attempt_provider_chek_card_id'))
        batch_op.drop_index(batch_op.f('ix_payment_attempt_id'))
        batch_op.drop_index(batch_op.f('ix_payment_attempt_family_chek_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_attempt_card_transfer_id'))
        batch_op.drop_index(batch_op.f('ix_payment_attempt_ach_payment_id'))

    op.drop_table('payment_attempt')
    with op.batch_alter_table('payment_intent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_intent_provider_external_id'))
        batch_op.drop_index(batch_op.f('ix_payment_intent_child_external_id'))

    op.drop_table('payment_intent')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_external_provider_id'))
        batch_op.drop_index(batch_op.f('ix_payment_external_child_id'))

    op.drop_table('payment')
    with op.batch_alter_table('provider_payment_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_payment_settings_provider_external_id'))
        batch_op.drop_index(batch_op.f('ix_provider_payment_settings_id'))
        batch_op.drop_index(batch_op.f('ix_provider_payment_settings_chek_user_id'))
        batch_op.drop_index(batch_op.f('ix_provider_payment_settings_chek_direct_pay_id'))
        batch_op.drop_index(batch_op.f('ix_provider_payment_settings_chek_card_id'))

    op.drop_table('provider_payment_settings')
    with op.batch_alter_table('family_payment_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_payment_settings_id'))
        batch_op.drop_index(batch_op.f('ix_family_payment_settings_family_external_id'))
        batch_op.drop_index(batch_op.f('ix_family_payment_settings_chek_user_id'))

    op.drop_table('family_payment_settings')
    # ### end Alembic commands ###
