"""Update payment request, add MonthAllocation, AllocatedCareDay, PaymentRate

Revision ID: 76165844bd1c
Revises: fdad39e7d357
Create Date: 2025-07-31 20:18:25.664284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '76165844bd1c'
down_revision = 'fdad39e7d357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('month_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('allocation_cents', sa.Integer(), nullable=False),
    sa.Column('google_sheets_child_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sheets_child_id', 'date', name='unique_child_month')
    )
    with op.batch_alter_table('month_allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_month_allocation_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_month_allocation_google_sheets_child_id'), ['google_sheets_child_id'], unique=False)

    op.create_table('payment_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sheets_provider_id', sa.Integer(), nullable=False),
    sa.Column('google_sheets_child_id', sa.Integer(), nullable=False),
    sa.Column('half_day_rate_cents', sa.Integer(), nullable=False),
    sa.Column('full_day_rate_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sheets_provider_id', 'google_sheets_child_id', name='unique_provider_child_rate')
    )
    with op.batch_alter_table('payment_rate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_rate_google_sheets_child_id'), ['google_sheets_child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_rate_google_sheets_provider_id'), ['google_sheets_provider_id'], unique=False)

    op.create_table('allocated_care_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_month_allocation_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('FULL_DAY', 'HALF_DAY', name='caredaytype'), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('provider_google_sheets_id', sa.Integer(), nullable=False),
    sa.Column('payment_distribution_requested', sa.Boolean(), nullable=True),
    sa.Column('last_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('locked_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['care_month_allocation_id'], ['month_allocation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('care_month_allocation_id', 'date', name='unique_allocation_date')
    )
    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocated_care_day_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocated_care_day_provider_google_sheets_id'), ['provider_google_sheets_id'], unique=False)

    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('care_days_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('care_day_ids', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_request_google_sheets_child_id'), ['google_sheets_child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_request_google_sheets_provider_id'), ['google_sheets_provider_id'], unique=False)
        batch_op.drop_column('hours')
        batch_op.drop_column('email_sent_successfully')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent_successfully', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_payment_request_google_sheets_provider_id'))
        batch_op.drop_index(batch_op.f('ix_payment_request_google_sheets_child_id'))
        batch_op.drop_column('care_day_ids')
        batch_op.drop_column('care_days_count')

    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocated_care_day_provider_google_sheets_id'))
        batch_op.drop_index(batch_op.f('ix_allocated_care_day_date'))

    op.drop_table('allocated_care_day')
    with op.batch_alter_table('payment_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_rate_google_sheets_provider_id'))
        batch_op.drop_index(batch_op.f('ix_payment_rate_google_sheets_child_id'))

    op.drop_table('payment_rate')
    with op.batch_alter_table('month_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_month_allocation_google_sheets_child_id'))
        batch_op.drop_index(batch_op.f('ix_month_allocation_date'))

    op.drop_table('month_allocation')
    # ### end Alembic commands ###
