"""paymen model fks

Revision ID: 78319a1f4b90
Revises: f7b73590f93b
Create Date: 2025-08-28 23:11:37.917498

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "78319a1f4b90"
down_revision = "f7b73590f93b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_attempt", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_intent_id", sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column("payment_id", sa.UUID(), nullable=True))
        batch_op.create_foreign_key("fk_payment_attempt_intent_id", "payment_intent", ["payment_intent_id"], ["id"])
        batch_op.create_foreign_key("fk_payment_attempt_payment_id", "payment", ["payment_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_attempt", schema=None) as batch_op:
        batch_op.drop_constraint("fk_payment_attempt_payment_id", type_="foreignkey")
        batch_op.drop_constraint("fk_payment_attempt_intent_id", type_="foreignkey")
        batch_op.drop_column("payment_id")
        batch_op.drop_column("payment_intent_id")

    # ### end Alembic commands ###
