"""payment models fk

Revision ID: 88278629a5bc
Revises: 74fb34cdd755
Create Date: 2025-08-29 18:58:01.884442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88278629a5bc'
down_revision = '74fb34cdd755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_intent_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('successful_attempt_id', sa.UUID(), nullable=False))
        batch_op.create_unique_constraint(None, ['payment_intent_id'])
        batch_op.create_foreign_key('fk_payment_successful_attempt_id', 'payment_attempt', ['successful_attempt_id'], ['id'])
        batch_op.create_foreign_key('fk_payment_intent_id', 'payment_intent', ['payment_intent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_intent_id', type_='foreignkey')
        batch_op.drop_constraint('fk_payment_successful_attempt_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('successful_attempt_id')
        batch_op.drop_column('payment_intent_id')

    # ### end Alembic commands ###
