"""more changes again

Revision ID: 8d64fe1ae862
Revises: 78319a1f4b90
Create Date: 2025-08-29 13:41:18.165815

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8d64fe1ae862"
down_revision = "78319a1f4b90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_chek_card_id"))
        batch_op.drop_index(batch_op.f("ix_payment_chek_direct_pay_id"))
        batch_op.drop_index(batch_op.f("ix_payment_chek_transfer_id"))
        batch_op.drop_index(batch_op.f("ix_payment_chek_user_id"))
        batch_op.drop_column("chek_user_id")
        batch_op.drop_column("chek_card_id")
        batch_op.drop_column("chek_transfer_id")
        batch_op.drop_column("chek_direct_pay_id")

    with op.batch_alter_table("payment_attempt", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chek_user_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("chek_card_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("chek_direct_pay_id", sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f("ix_payment_attempt_chek_card_id"), ["chek_card_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_attempt_chek_direct_pay_id"), ["chek_direct_pay_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_attempt_chek_user_id"), ["chek_user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_attempt_chek_user_id"))
        batch_op.drop_index(batch_op.f("ix_payment_attempt_chek_direct_pay_id"))
        batch_op.drop_index(batch_op.f("ix_payment_attempt_chek_card_id"))
        batch_op.drop_column("chek_direct_pay_id")
        batch_op.drop_column("chek_card_id")
        batch_op.drop_column("chek_user_id")

    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chek_direct_pay_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("chek_transfer_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("chek_card_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("chek_user_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f("ix_payment_chek_user_id"), ["chek_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_chek_transfer_id"), ["chek_transfer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_chek_direct_pay_id"), ["chek_direct_pay_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_chek_card_id"), ["chek_card_id"], unique=False)

    # ### end Alembic commands ###
