"""add_supabase_ids

Revision ID: 94fce4895be6
Revises: 35e5058b5596
Create Date: 2025-09-08 21:52:26.768169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fce4895be6'
down_revision = '35e5058b5596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_supabase_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('provider_google_sheets_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_allocated_care_day_provider_supabase_id'), ['provider_supabase_id'], unique=False)

    with op.batch_alter_table('allocated_lump_sum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_supabase_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('provider_google_sheets_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_allocated_lump_sum_provider_supabase_id'), ['provider_supabase_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_supabase_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('provider_supabase_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_attendance_child_supabase_id'), ['child_supabase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_provider_supabase_id'), ['provider_supabase_id'], unique=False)

    with op.batch_alter_table('family_invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_supabase_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_family_invitation_provider_supabase_id'), ['provider_supabase_id'], unique=False)

    with op.batch_alter_table('family_payment_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_supabase_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_family_payment_settings_family_supabase_id'), ['family_supabase_id'], unique=False)

    with op.batch_alter_table('month_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_supabase_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_month_allocation_child_supabase_id'), ['child_supabase_id'], unique=False)

    with op.batch_alter_table('payment_intent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_supabase_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('child_supabase_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('provider_external_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_payment_intent_child_supabase_id'), ['child_supabase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_intent_provider_supabase_id'), ['provider_supabase_id'], unique=False)

    with op.batch_alter_table('payment_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_supabase_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('child_supabase_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('google_sheets_provider_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_payment_rate_child_supabase_id'), ['child_supabase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_rate_provider_supabase_id'), ['provider_supabase_id'], unique=False)

    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_supabase_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('child_supabase_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('google_sheets_provider_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_payment_request_child_supabase_id'), ['child_supabase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_request_provider_supabase_id'), ['provider_supabase_id'], unique=False)

    with op.batch_alter_table('provider_invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_supabase_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_provider_invitation_child_supabase_id'), ['child_supabase_id'], unique=False)

    with op.batch_alter_table('provider_payment_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_supabase_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_provider_payment_settings_provider_supabase_id'), ['provider_supabase_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_payment_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_payment_settings_provider_supabase_id'))
        batch_op.drop_column('provider_supabase_id')

    with op.batch_alter_table('provider_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_invitation_child_supabase_id'))
        batch_op.drop_column('child_supabase_id')

    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_request_provider_supabase_id'))
        batch_op.drop_index(batch_op.f('ix_payment_request_child_supabase_id'))
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('google_sheets_provider_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('child_supabase_id')
        batch_op.drop_column('provider_supabase_id')

    with op.batch_alter_table('payment_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_rate_provider_supabase_id'))
        batch_op.drop_index(batch_op.f('ix_payment_rate_child_supabase_id'))
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('google_sheets_provider_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('child_supabase_id')
        batch_op.drop_column('provider_supabase_id')

    with op.batch_alter_table('payment_intent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_intent_provider_supabase_id'))
        batch_op.drop_index(batch_op.f('ix_payment_intent_child_supabase_id'))
        batch_op.alter_column('provider_external_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('child_supabase_id')
        batch_op.drop_column('provider_supabase_id')

    with op.batch_alter_table('month_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_month_allocation_child_supabase_id'))
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('child_supabase_id')

    with op.batch_alter_table('family_payment_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_payment_settings_family_supabase_id'))
        batch_op.drop_column('family_supabase_id')

    with op.batch_alter_table('family_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_invitation_provider_supabase_id'))
        batch_op.drop_column('provider_supabase_id')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_provider_supabase_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_child_supabase_id'))
        batch_op.drop_column('provider_supabase_id')
        batch_op.drop_column('child_supabase_id')

    with op.batch_alter_table('allocated_lump_sum', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocated_lump_sum_provider_supabase_id'))
        batch_op.alter_column('provider_google_sheets_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('provider_supabase_id')

    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocated_care_day_provider_supabase_id'))
        batch_op.alter_column('provider_google_sheets_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('provider_supabase_id')

    # ### end Alembic commands ###
