"""Remove locked_date field

Revision ID: 9ee0cfc6b76f
Revises: c0aac583d940
Create Date: 2025-08-28 20:33:00.505481

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9ee0cfc6b76f"
down_revision = "c0aac583d940"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocated_care_day", schema=None) as batch_op:
        batch_op.drop_column("locked_date")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocated_care_day", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("locked_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
