"""Email provider updates

Revision ID: a0a5607af8ee
Revises: 1d5324678518
Create Date: 2025-10-13 19:03:45.180447

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0a5607af8ee"
down_revision = "1d5324678518"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_record", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email_provider", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("provider_message_id", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("provider_status_code", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_email_record_email_provider"), ["email_provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_record_provider_message_id"), ["provider_message_id"], unique=False)
        batch_op.drop_column("sendgrid_status_code")
        batch_op.drop_column("sendgrid_message_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_record", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sendgrid_message_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True)
        )
        batch_op.add_column(sa.Column("sendgrid_status_code", sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f("ix_email_record_provider_message_id"))
        batch_op.drop_index(batch_op.f("ix_email_record_email_provider"))
        batch_op.drop_column("provider_status_code")
        batch_op.drop_column("provider_message_id")
        batch_op.drop_column("email_provider")

    # ### end Alembic commands ###
