"""Add household and provider models

Revision ID: a7b4f20c5e17
Revises: 
Create Date: 2025-07-21 18:22:14.649107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b4f20c5e17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sheet_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caregiver_google_sheet_id'), ['google_sheet_id'], unique=True)

    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sheet_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_google_sheet_id'), ['google_sheet_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_google_sheet_id'))

    op.drop_table('household')
    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caregiver_google_sheet_id'))

    op.drop_table('caregiver')
    # ### end Alembic commands ###
