"""lump sum track days

Revision ID: af5c75ad4789
Revises: d458ce0f02ff
Create Date: 2025-10-01 20:11:32.551952

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "af5c75ad4789"
down_revision = "d458ce0f02ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocated_lump_sum", schema=None) as batch_op:
        batch_op.add_column(sa.Column("days", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("half_days", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocated_lump_sum", schema=None) as batch_op:
        batch_op.drop_column("half_days")
        batch_op.drop_column("days")

    # ### end Alembic commands ###
