"""Make care_days_count on PaymentRequest nullable=False

Revision ID: b07913da7ef4
Revises: 76165844bd1c
Create Date: 2025-07-31 20:26:03.001303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07913da7ef4'
down_revision = '76165844bd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.alter_column('care_days_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.alter_column('care_days_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
