"""Update google sheet ids to be strings

Revision ID: c7037570b095
Revises: ff81a8277415
Create Date: 2025-08-07 14:47:50.375451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7037570b095'
down_revision = 'ff81a8277415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.alter_column('provider_google_sheets_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('month_allocation', schema=None) as batch_op:
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('payment_rate', schema=None) as batch_op:
        batch_op.alter_column('google_sheets_provider_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.alter_column('google_sheets_provider_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('google_sheets_provider_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('payment_rate', schema=None) as batch_op:
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('google_sheets_provider_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('month_allocation', schema=None) as batch_op:
        batch_op.alter_column('google_sheets_child_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.alter_column('provider_google_sheets_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
