"""email record model

Revision ID: d458ce0f02ff
Revises: e8385996b8f1
Create Date: 2025-09-24 21:40:56.253207

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d458ce0f02ff"
down_revision = "e8385996b8f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bulk_email_batch",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_name", sa.String(length=255), nullable=False),
        sa.Column("batch_type", sa.String(length=100), nullable=True),
        sa.Column("total_recipients", sa.Integer(), nullable=False),
        sa.Column("successful_sends", sa.Integer(), nullable=False),
        sa.Column("failed_sends", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("from_email", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("batch_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bulk_email_batch", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bulk_email_batch_status"), ["status"], unique=False)

    op.create_table(
        "email_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("from_email", sa.String(length=255), nullable=False),
        sa.Column("to_emails", sa.ARRAY(sa.String(length=255)), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("html_content", sa.Text(), nullable=False),
        sa.Column("from_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("sendgrid_message_id", sa.String(length=100), nullable=True),
        sa.Column("sendgrid_status_code", sa.Integer(), nullable=True),
        sa.Column("email_type", sa.String(length=50), nullable=True),
        sa.Column("context_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("bulk_batch_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bulk_batch_id"],
            ["bulk_email_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_email_record_email_type"), ["email_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_record_from_email"), ["from_email"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_record_is_internal"), ["is_internal"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_record_status"), ["status"], unique=False)

    with op.batch_alter_table("payment_rate", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("unique_provider_child_rate"), type_="unique")
        batch_op.create_unique_constraint("unique_provider_child_rate", ["provider_supabase_id", "child_supabase_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_rate", schema=None) as batch_op:
        batch_op.drop_constraint("unique_provider_child_rate", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("unique_provider_child_rate"),
            ["google_sheets_provider_id", "google_sheets_child_id"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("email_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_record_status"))
        batch_op.drop_index(batch_op.f("ix_email_record_is_internal"))
        batch_op.drop_index(batch_op.f("ix_email_record_from_email"))
        batch_op.drop_index(batch_op.f("ix_email_record_email_type"))

    op.drop_table("email_record")
    with op.batch_alter_table("bulk_email_batch", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bulk_email_batch_status"))

    op.drop_table("bulk_email_batch")
    # ### end Alembic commands ###
