"""partial payment

Revision ID: d6434d09ed2f
Revises: a0a5607af8ee
Create Date: 2025-12-01 19:52:47.221905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6434d09ed2f'
down_revision = 'a0a5607af8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_missing_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.drop_column('amount_missing_cents')

    # ### end Alembic commands ###
