"""provider openned at

Revision ID: d6dbe3934f81
Revises: 4bc01c5a2653
Create Date: 2025-08-18 10:37:59.828898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6dbe3934f81'
down_revision = '4bc01c5a2653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column(
            'opened_at',
            new_column_name='family_opened_at',
            existing_type=sa.DateTime(),
            existing_nullable=True,
        )
        batch_op.add_column(sa.Column('provider_opened_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('provider_opened_at')
        batch_op.alter_column(
            'family_opened_at',
            new_column_name='opened_at',
            existing_type=sa.DateTime(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
