"""family invitation

Revision ID: dc10561d5d88
Revises: 2db51e2690c4
Create Date: 2025-08-06 12:12:46.371782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc10561d5d88'
down_revision = '2db51e2690c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=True),
    sa.Column('provider_google_sheet_id', sa.String(length=64), nullable=True),
    sa.Column('invite_email', sa.String(length=254), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('sms_sent', sa.Boolean(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_invitation_provider_google_sheet_id'), ['provider_google_sheet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_invitation_public_id'), ['public_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_invitation_public_id'))
        batch_op.drop_index(batch_op.f('ix_family_invitation_provider_google_sheet_id'))

    op.drop_table('family_invitation')
    # ### end Alembic commands ###
