"""attendance_days

Revision ID: e7f96bcb63e2
Revises: e8385996b8f1
Create Date: 2025-09-25 23:09:24.137356

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e7f96bcb63e2"
down_revision = "e8385996b8f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("family_entered_full_days", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("family_entered_half_days", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("provider_entered_full_days", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("provider_entered_half_days", sa.Integer(), nullable=True))

    with op.batch_alter_table("payment_rate", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("unique_provider_child_rate"), type_="unique")
        batch_op.create_unique_constraint("unique_provider_child_rate", ["provider_supabase_id", "child_supabase_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_rate", schema=None) as batch_op:
        batch_op.drop_constraint("unique_provider_child_rate", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("unique_provider_child_rate"),
            ["google_sheets_provider_id", "google_sheets_child_id"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.drop_column("provider_entered_half_days")
        batch_op.drop_column("provider_entered_full_days")
        batch_op.drop_column("family_entered_half_days")
        batch_op.drop_column("family_entered_full_days")

    # ### end Alembic commands ###
