"""empty message

Revision ID: e8385996b8f1
Revises: 94fce4895be6
Create Date: 2025-09-09 17:14:54.643899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8385996b8f1'
down_revision = '94fce4895be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_allocation_provider_date'), type_='unique')
        batch_op.create_unique_constraint('unique_allocation_provider_date', ['care_month_allocation_id', 'provider_supabase_id', 'date'])

    with op.batch_alter_table('month_allocation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_child_month'), type_='unique')
        batch_op.create_unique_constraint('unique_child_month', ['child_supabase_id', 'date'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_supabase_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('child_supabase_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('external_provider_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_payment_child_supabase_id'), ['child_supabase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_provider_supabase_id'), ['provider_supabase_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_provider_supabase_id'))
        batch_op.drop_index(batch_op.f('ix_payment_child_supabase_id'))
        batch_op.alter_column('external_provider_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('child_supabase_id')
        batch_op.drop_column('provider_supabase_id')

    with op.batch_alter_table('month_allocation', schema=None) as batch_op:
        batch_op.drop_constraint('unique_child_month', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_child_month'), ['google_sheets_child_id', 'date'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('allocated_care_day', schema=None) as batch_op:
        batch_op.drop_constraint('unique_allocation_provider_date', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_allocation_provider_date'), ['care_month_allocation_id', 'provider_google_sheets_id', 'date'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
