"""payment models foreign keys

Revision ID: f5e88d40d915
Revises: 87e8d8054e18
Create Date: 2025-08-28 04:38:41.348778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e88d40d915'
down_revision = '87e8d8054e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_attempt', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'payment', ['payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_attempt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
