"""payment models

Revision ID: f7b73590f93b
Revises: 9ee0cfc6b76f
Create Date: 2025-08-28 23:10:55.845194

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f7b73590f93b"
down_revision = "9ee0cfc6b76f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_attempt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("payment_method", sa.Enum("CARD", "ACH", name="paymentmethod"), nullable=False),
        sa.Column("wallet_transfer_id", sa.String(length=64), nullable=True),
        sa.Column("wallet_transfer_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ach_payment_id", sa.String(length=64), nullable=True),
        sa.Column("ach_payment_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payment_attempt", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payment_attempt_ach_payment_id"), ["ach_payment_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_attempt_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_attempt_wallet_transfer_id"), ["wallet_transfer_id"], unique=False)

    op.create_table(
        "provider_payment_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_external_id", sa.String(length=64), nullable=True),
        sa.Column("chek_user_id", sa.String(length=64), nullable=True),
        sa.Column("chek_direct_pay_id", sa.String(length=64), nullable=True),
        sa.Column("chek_direct_pay_status", sa.String(length=32), nullable=True),
        sa.Column("chek_card_id", sa.String(length=64), nullable=True),
        sa.Column("chek_card_status", sa.String(length=32), nullable=True),
        sa.Column("chek_wallet_balance", sa.Integer(), nullable=True),
        sa.Column("payment_method", sa.Enum("CARD", "ACH", name="paymentmethod"), nullable=True),
        sa.Column("payment_method_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_chek_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("provider_payment_settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_provider_payment_settings_chek_card_id"), ["chek_card_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_provider_payment_settings_chek_direct_pay_id"), ["chek_direct_pay_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_provider_payment_settings_chek_user_id"), ["chek_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_provider_payment_settings_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_provider_payment_settings_provider_external_id"), ["provider_external_id"], unique=False
        )

    op.create_table(
        "payment_intent",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_external_id", sa.String(length=64), nullable=False),
        sa.Column("child_external_id", sa.String(length=64), nullable=True),
        sa.Column("month_allocation_id", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("care_day_ids", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("lump_sum_ids", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_payment_settings_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["month_allocation_id"], ["month_allocation.id"], name="fk_payment_intent_month_allocation_id"
        ),
        sa.ForeignKeyConstraint(
            ["provider_payment_settings_id"],
            ["provider_payment_settings.id"],
            name="fk_payment_intent_provider_settings_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payment_intent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payment_intent_child_external_id"), ["child_external_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_payment_intent_provider_external_id"), ["provider_external_id"], unique=False
        )

    op.create_table(
        "payment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payment_intent_id", sa.UUID(), nullable=False),
        sa.Column("successful_attempt_id", sa.UUID(), nullable=False),
        sa.Column("external_provider_id", sa.String(length=64), nullable=False),
        sa.Column("external_child_id", sa.String(length=64), nullable=True),
        sa.Column("provider_payment_settings_id", sa.UUID(), nullable=False),
        sa.Column("chek_user_id", sa.String(length=64), nullable=True),
        sa.Column("chek_direct_pay_id", sa.String(length=64), nullable=True),
        sa.Column("chek_card_id", sa.String(length=64), nullable=True),
        sa.Column("chek_transfer_id", sa.String(length=64), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("payment_method", sa.Enum("CARD", "ACH", name="paymentmethod"), nullable=False),
        sa.Column("month_allocation_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["month_allocation_id"], ["month_allocation.id"], name="fk_payment_month_allocation_id"
        ),
        sa.ForeignKeyConstraint(["payment_intent_id"], ["payment_intent.id"], name="fk_payment_intent_id"),
        sa.ForeignKeyConstraint(
            ["provider_payment_settings_id"], ["provider_payment_settings.id"], name="fk_payment_provider_settings_id"
        ),
        sa.ForeignKeyConstraint(
            ["successful_attempt_id"], ["payment_attempt.id"], name="fk_payment_successful_attempt_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_intent_id"),
    )
    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payment_chek_card_id"), ["chek_card_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_chek_direct_pay_id"), ["chek_direct_pay_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_chek_transfer_id"), ["chek_transfer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_chek_user_id"), ["chek_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_external_child_id"), ["external_child_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_external_provider_id"), ["external_provider_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_id"), ["id"], unique=False)

    with op.batch_alter_table("allocated_care_day", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_id", sa.UUID(), nullable=True))
        batch_op.create_foreign_key("fk_allocated_care_day_payment_id", "payment", ["payment_id"], ["id"])

    with op.batch_alter_table("allocated_lump_sum", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_id", sa.UUID(), nullable=True))
        batch_op.create_foreign_key("fk_allocated_lump_sum_payment_id", "payment", ["payment_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocated_lump_sum", schema=None) as batch_op:
        batch_op.drop_constraint("fk_allocated_lump_sum_payment_id", type_="foreignkey")
        batch_op.drop_column("payment_id")

    with op.batch_alter_table("allocated_care_day", schema=None) as batch_op:
        batch_op.drop_constraint("fk_allocated_care_day_payment_id", type_="foreignkey")
        batch_op.drop_column("payment_id")

    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_id"))
        batch_op.drop_index(batch_op.f("ix_payment_external_provider_id"))
        batch_op.drop_index(batch_op.f("ix_payment_external_child_id"))
        batch_op.drop_index(batch_op.f("ix_payment_chek_user_id"))
        batch_op.drop_index(batch_op.f("ix_payment_chek_transfer_id"))
        batch_op.drop_index(batch_op.f("ix_payment_chek_direct_pay_id"))
        batch_op.drop_index(batch_op.f("ix_payment_chek_card_id"))

    op.drop_table("payment")
    with op.batch_alter_table("payment_intent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_intent_provider_external_id"))
        batch_op.drop_index(batch_op.f("ix_payment_intent_child_external_id"))

    op.drop_table("payment_intent")
    with op.batch_alter_table("provider_payment_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_payment_settings_provider_external_id"))
        batch_op.drop_index(batch_op.f("ix_provider_payment_settings_id"))
        batch_op.drop_index(batch_op.f("ix_provider_payment_settings_chek_user_id"))
        batch_op.drop_index(batch_op.f("ix_provider_payment_settings_chek_direct_pay_id"))
        batch_op.drop_index(batch_op.f("ix_provider_payment_settings_chek_card_id"))

    op.drop_table("provider_payment_settings")
    with op.batch_alter_table("payment_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_attempt_wallet_transfer_id"))
        batch_op.drop_index(batch_op.f("ix_payment_attempt_id"))
        batch_op.drop_index(batch_op.f("ix_payment_attempt_ach_payment_id"))

    op.drop_table("payment_attempt")
    # ### end Alembic commands ###
