"""family invitation

Revision ID: f809a5b2bc15
Revises: c7037570b095
Create Date: 2025-08-08 11:30:00.777364

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f809a5b2bc15"
down_revision = "c7037570b095"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family_invitation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=True),
        sa.Column("provider_google_sheet_id", sa.String(length=64), nullable=True),
        sa.Column("invite_email", sa.String(length=254), nullable=False),
        sa.Column("email_sent", sa.Boolean(), nullable=False),
        sa.Column("sms_sent", sa.Boolean(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("family_invitation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_family_invitation_provider_google_sheet_id"), ["provider_google_sheet_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_family_invitation_public_id"), ["public_id"], unique=False)

    with op.batch_alter_table("allocated_care_day", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_allocated_care_day_provider_google_sheets_id"), ["provider_google_sheets_id"], unique=False
        )
        batch_op.create_unique_constraint(
            "unique_allocation_provider_date", ["care_month_allocation_id", "provider_google_sheets_id", "date"]
        )

    with op.batch_alter_table("month_allocation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_month_allocation_google_sheets_child_id"), ["google_sheets_child_id"], unique=False
        )
        batch_op.create_unique_constraint("unique_child_month", ["google_sheets_child_id", "date"])

    with op.batch_alter_table("payment_rate", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payment_rate_google_sheets_child_id"), ["google_sheets_child_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payment_rate_google_sheets_provider_id"), ["google_sheets_provider_id"], unique=False
        )
        batch_op.create_unique_constraint(
            "unique_provider_child_rate", ["google_sheets_provider_id", "google_sheets_child_id"]
        )

    with op.batch_alter_table("payment_request", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payment_request_google_sheets_child_id"), ["google_sheets_child_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payment_request_google_sheets_provider_id"), ["google_sheets_provider_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_request_google_sheets_provider_id"))
        batch_op.drop_index(batch_op.f("ix_payment_request_google_sheets_child_id"))

    with op.batch_alter_table("payment_rate", schema=None) as batch_op:
        batch_op.drop_constraint("unique_provider_child_rate", type_="unique")
        batch_op.drop_index(batch_op.f("ix_payment_rate_google_sheets_provider_id"))
        batch_op.drop_index(batch_op.f("ix_payment_rate_google_sheets_child_id"))

    with op.batch_alter_table("month_allocation", schema=None) as batch_op:
        batch_op.drop_constraint("unique_child_month", type_="unique")
        batch_op.drop_index(batch_op.f("ix_month_allocation_google_sheets_child_id"))

    with op.batch_alter_table("allocated_care_day", schema=None) as batch_op:
        batch_op.drop_constraint("unique_allocation_provider_date", type_="unique")
        batch_op.drop_index(batch_op.f("ix_allocated_care_day_provider_google_sheets_id"))

    with op.batch_alter_table("family_invitation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_family_invitation_public_id"))
        batch_op.drop_index(batch_op.f("ix_family_invitation_provider_google_sheet_id"))

    op.drop_table("family_invitation")
    # ### end Alembic commands ###
