"""Add payment request model

Revision ID: fdad39e7d357
Revises: ba142e5257d0
Create Date: 2025-07-23 23:33:22.246042

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fdad39e7d357"
down_revision = "ba142e5257d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("google_sheets_provider_id", sa.Integer(), nullable=False),
        sa.Column("google_sheets_child_id", sa.Integer(), nullable=False),
        sa.Column("amount_in_cents", sa.Integer(), nullable=False),
        sa.Column("hours", sa.Float(), nullable=False),
        sa.Column("email_sent_successfully", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_request")
    # ### end Alembic commands ###
