"""Remove Family and Provider

Revision ID: ff81a8277415
Revises: 2db51e2690c4
Create Date: 2025-08-07 12:22:10.654084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff81a8277415'
down_revision = '2db51e2690c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_google_sheet_id'))

    op.drop_table('family')
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_google_sheet_id'))

    op.drop_table('provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('google_sheet_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_pkey'))
    )
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_google_sheet_id'), ['google_sheet_id'], unique=True)

    op.create_table('family',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('google_sheet_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('family_pkey'))
    )
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_google_sheet_id'), ['google_sheet_id'], unique=True)

    # ### end Alembic commands ###
