name: Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a compatible Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run lint
      run: make lint
